# Generated by Django 3.0.4 on 2020-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20200320_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='member',
        ),
    ]
