# Generated by Django 3.0.4 on 2020-03-20 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0007_auto_20200320_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='member',
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
    ]
